djangolearn/urls.py
from django.contrib import admin
from django.urls import path, include # include for routing app directly to other App's view

from djangolearn.views import home_view, NewHomeView  # from .views import home_view
from firstapp.views import (
    show_data, create_entry, show_data_slug
)
from accounts.views import (
    login_view, logout_view, register_view
)
from django.conf import settings
from django.conf.urls.static import static

# try To keep it in Alphabetical order
urlpatterns = [
    path('admin/', admin.site.urls), # default
    # path('', NewHomeView.as_view()), # for class base view
    path('', home_view),
    path('drf/', include('restframeworklearn.urls')),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
    path('user/', include('firstapp.urls')),
    path('ecommerce/', include('store.urls')), # re_path also used in to make using Regular Expressions which is complex
    path('recipes/', include('recipes.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this ill allowed to create automatic URL to image

# order in urlpatterns dose matter # make nates in .md file
# 1. user/    2. user/anything    3. user/<datatype:variablename>

firstapp/urls.py
from django.urls import path

from .views import (
    show_data, create_entry, show_data_slug
)

app_name='firstapp'
urlpatterns = [
    path('', show_data),
    path('create/', create_entry, name='create'),
    path('<int:id>/', show_data, name='show'),
    path('<slug:slug>/', show_data_slug, name='show-slug'),
]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('insert_product/', views.insert_product, name='insert_product'),

    path('add_item/', views.add_item, name='add_item'),
    path('cart/add_item/', views.add_item),
    path('process_order/', views.process_order, name='process_order'),
    path('checkout/process_order/', views.process_order),
]

templates/home-view.html
{% extends "index.html" %}
<!-- curlly breckets works in link also all most at everywhere in HTML it works-->

{% block content %}
    <h1 style="text-align:center"> Hello {{name}}! </h1>

    <!-- inputs -->
    <form action="user/" method="GET"> <!-- url is passed in 'action' and when we submit request that handle by that url -->
        <input type="text" name="query" placeholder="ID or Title"/> <!-- every input need name, except submit which create "key : value" pass data based on method of form -->
        <input type="submit"/>
    </form>


    <br>
    <!-- Use of URL Reverse in Template : we can not use "firstapp:show-slug" & "firstapp:show" Here because this URL need data also to insert  -->
    <!-- We should use only Urls like "firstapp:show-slug" & "firstapp:show" when we want to redirect to Fix page Like below -->
    <!--    <h3>GO to <a href="{% url 'firstapp:show-slug' slug='hello-world' %}">Hello World</a> page</h3>-->
    <h3>Click Here to :- <a href="{% url 'firstapp:create' %}">Create User Data</a></h3>
    <!-- Displaying Output  -->
    {% for row in model_data %}
        {% if row.title and row.content %} <!-- How to check multi conditions with operators ???? -->
            <h2><a href="/user/{{row.id}}/">Title : {{row.title}}</a></h2>
            <p> <a href="/user/{{row.slug}}/">Slug : {{row.slug}}</a></p>
            <p> <a href="{{row.get_absolute_url}}">Content : {{row.content}}</a></p>
        {% endif %}
    {% endfor %}

{% endblock content%}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>
<body class="main-body">
    {% block content %}
    {% endblock %}
</body>
</html>