djangolearn/urls.py
from django.contrib import admin
from django.urls import path, include # include for routing app directly to other App's view

from djangolearn.views import home_view, NewHomeView  # from .views import home_view
from firstapp.views import (
    show_data, create_entry, show_data_slug
)
from accounts.views import (
    login_view, logout_view, register_view
)
from django.conf import settings
from django.conf.urls.static import static

# try To keep it in Alphabetical order
urlpatterns = [
    path('admin/', admin.site.urls), # default
    # path('', NewHomeView.as_view()), # for class base view
    path('', home_view),
    path('drf/', include('restframeworklearn.urls')),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
    path('user/', include('firstapp.urls')),
    path('ecommerce/', include('store.urls')), # re_path also used in to make using Regular Expressions which is complex
    path('recipes/', include('recipes.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this ill allowed to create automatic URL to image

# order in urlpatterns dose matter # make nates in .md file
# 1. user/    2. user/anything    3. user/<datatype:variablename>

recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view, recipe_detail_view, recipe_create_view, recipe_update_view, recipe_delete_view, recipe_ingredient_delete_view
)

app_name = 'recipes'
urlpatterns = [
    path('', recipe_list_view, name='list'),
    path('create/', recipe_create_view, name='create'),
    path('<int:id>/', recipe_detail_view, name='detail'),
    path('update/<int:id>/', recipe_update_view, name='update'),
    path('delete/<int:id>/', recipe_delete_view, name='delete'),
    path('delete/<int:parent_id>/<int:id>', recipe_ingredient_delete_view, name='ingredient-delete'),
]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('insert_product/', views.insert_product, name='insert_product'),

    path('add_item/', views.add_item, name='add_item'),
    path('cart/add_item/', views.add_item),
    path('process_order/', views.process_order, name='process_order'),
    path('checkout/process_order/', views.process_order),
]

recipes/models.py
import pint
from django.conf import settings
from django.urls import reverse
from django.db import models
from .validators import validate_unit_of_measure
from .utils import number_str_to_float

# Create your models here.

class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=220)
    description = models.TextField(blank=True, null=True)
    directions = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={'id':self.id})

    def get_update_url(self):
        return reverse("recipes:update", kwargs={'id':self.id})

    def get_delete_url(self):
        return reverse("recipes:delete", kwargs={'id':self.id})

    @property
    def get_ingredients(self):
        ingredients = self.recipeingredient_set.all()
        return ingredients

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=220)
    description = models.TextField(blank=True, null=True)
    quantity = models.CharField(max_length=50)  # 1 and 1/4
    quantity_as_float = models.FloatField(max_length=50, blank=True, null=True)  # 1.25
    unit = models.CharField(max_length=50, validators=[validate_unit_of_measure])  # KG, gram, pounds, lbs, spoon
    directions = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return self.recipe.get_absolute_url()

    def get_delete_url(self):
        kwargs={
                'parent_id': self.recipe.id,
                'id': self.id
        }
        return reverse("recipes:ingredient-delete", kwargs=kwargs)

    # TODO : Because of conversion system [as_mks and as_imperial] it is working slow
    # it compute every time when we call detail page so it is taking time.
    def convert_to_system(self, system='mks'):
        if self.quantity_as_float is None:
            return None
        ureg = pint.UnitRegistry(system=system)
        measurement = self.quantity_as_float * ureg[self.unit]
        return measurement  # .to_base_units()

    def as_mks(self):
        # meter, kilogram, second
        measurement = self.convert_to_system(system='msk')
        print(f'kilogram : {measurement}')
        return measurement.to('kg')
        # return measurement.to_base_units()

    def as_imperial(self):
        # miles, pounds, second
        measurement = self.convert_to_system(system='imperial')
        print(f'pound : {measurement}')
        return measurement.to('pounds')
        # return measurement.to_base_units()

    def save(self, *args, **kwargs):
        qty = self.quantity
        qty_as_float, qty_as_float_success = number_str_to_float(qty)
        if qty_as_float_success:
            self.quantity_as_float = qty_as_float
        else:
            self.quantity_as_float = None
        super().save(*args, **kwargs)

recipes/forms.py
from django import forms

from .models import Recipe, RecipeIngredient

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'description', 'directions']

class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['name', 'quantity', 'unit']  # only pass columns

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.forms.models import modelformset_factory  # model form for query sets
from .models import Recipe, RecipeIngredient
from .forms import RecipeForm, RecipeIngredientForm


# Create your views here.
@login_required
def recipe_list_view(request, id=None):
    qs = Recipe.objects.filter(user=request.user)
    print(qs)
    context = {
        'object_list' : qs
    }
    return render(request, 'recipes/list.html', context)

@login_required
def recipe_detail_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    context = {
        'object': obj
    }
    return render(request, 'recipes/detail.html', context)

@login_required
def recipe_create_view(request, id=None):
    form = RecipeForm(request.POST or None)
    context = {
        'modelform' : form
    }
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        return redirect(obj.get_absolute_url())
    return render(request, 'recipes/create-update.html', context)

@login_required
def recipe_update_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    form = RecipeForm(request.POST or None, instance=obj)  # instance=obj with help of this form get data already exist.
    # initial = {'name' : 'Please input the name'}  it is also give data we want, while inserting it throw and error.
    RecipeIngredientFormSet = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=0)
    qs = obj.recipeingredient_set.all()
    formset = RecipeIngredientFormSet(request.POST or None, queryset=qs)
    context = {
        'modelform': form,
        'modelformset': formset,
        'object': obj
    }
    if request.method == 'POST':
        print(request.POST)
    if all([form.is_valid(), formset.is_valid()]):
        parent = form.save(commit=False)
        parent.save()
        for child_form in formset:
            child = child_form.save(commit=False)
            child.recipe = parent
            child.save()
        context['message'] = 'Data saved.'
    return render(request, 'recipes/create-update.html', context)

@login_required
def recipe_delete_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    if request.method == 'POST':
        obj.delete()
        success_url = reverse('recipes:list')
        return redirect(success_url)
    context = {
        'object': obj
    }
    return render(request, 'recipes/delete.html', context)\

@login_required
def recipe_ingredient_delete_view(request, parent_id=None, id=None):
    obj = get_object_or_404(RecipeIngredient, recipe__id=parent_id, id=id, recipe__user=request.user)
    if request.method == 'POST':
        obj.delete()
        success_url = reverse('recipes:detail', kwargs={'id': parent_id})
        return redirect(success_url)
    context = {
        'object': obj
    }
    return render(request, 'recipes/delete.html', context)

templates/recipes/create-update.html
{% extends 'index.html' %}

{% block content %}
    <style>
        .hidden {
            display: none
        }
    </style>

    {% if message %}
        <p>{{message}}</p>
    {% endif %}
    <div style="margin-top:30px;">
        <form action="" method="post">
            {% csrf_token %} <!-- using this we can use csrf_token in django -->
            <h3>From Using Django Model Form</h3>
            {{ modelform.as_p }} <!--we have to put B/W <form> TAG-->
            <div id="ingredient-form-list">
            {% if modelformset %}
                <h3>Ingredients</h3>
                {{ modelformset.management_form }}
                {% for i_form in modelformset%}
                    <div class="ingredient-form">
                        {{ i_form.as_p}}
                    </div>
                {% endfor %}
            </div>
            {% endif %}
            <div id="empty-form" class="hidden">
                {{ modelformset.empty_form.as_p }}
            </div>
            <button type="button" id="add-more">Add More</button>

            <button type="submit" name="django_model_form" style="margin-top:10px;">Save</button>
        </form>
    </div>

    <script>
        const addMoreBtn = document.getElementById("add-more")
        const totalNewForms = document.getElementById("id_form-TOTAL_FORMS") // form-TOTAL_FORMS
        addMoreBtn.addEventListener('click', add_new_form)

        function add_new_form(event){
            if (event){
                event.preventDefault()
            }
            const currentIngredientForms = document.getElementsByClassName("ingredient-form")
            const currentFormCount = currentIngredientForms.length // + 1

            // ingredient-form-list
            const formCopyTarget = document.getElementById("ingredient-form-list")
            const copyEmptyFormEl = document.getElementById("empty-form").cloneNode(true)
            copyEmptyFormEl.setAttribute('class', 'ingredient-form')  // changing class form hidden to ingredient-form
            copyEmptyFormEl.setAttribute('id', `form-${currentFormCount}`)  // adding uniq id
            const regex = new RegExp('__prefix__','g')
            copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
            totalNewForms.setAttribute('value', currentFormCount + 1)
            formCopyTarget.append(copyEmptyFormEl)
        }
    </script>

{% endblock content %}

templates/recipes/delete.html
{% extends "index.html" %}

{% block content %}
    <form action="{{ object.get_delete_url}}" method="post">
        {% csrf_token %}
        <p>Are you sure want to delete {{object.name}}</p>
        <button type="submit">Yes, Delete.</button>
    </form>
{% endblock content%}t %}

templates/recipes/detail.html
{% extends 'index.html' %}

{% block content %}

    <h2>Name : {{object.name}}
        <small><a href="{{ object.get_update_url}}">Edit</a></small>
        <small><a href="{{ object.get_delete_url}}">Delete</a></small>
    </h2>
    <p>description : {{object.description}}</p>
    <p>directions : {{object.directions}}</p>
    <ol>
    {% for ingredient in object.get_ingredients %}
        <li>
            <h3>{{ ingredient.name }}  <small><a href="{{ ingredient.get_delete_url}}">Delete</a></small></h3>
        </li>
    {% endfor %}
    </ol>
{% endblock content %}


<!--            <p>{{ ingredient.as_mks }}</p>-->
<!--            <p>{{ ingredient.as_imperial }}</p>-->

templates/recipes/list.html
{% extends "index.html" %}

{% block content %}
    <h1 style="text-align:center"> My Recipes </h1>
    <br>
    <h3>Click Here to :- <a href="{% url 'recipes:create' %}">Create Recipes</a></h3>
    <!-- Displaying Output  -->
    <ul>
    {% for row in object_list %}
        <li>
            <h2><a href="{{row.get_absolute_url}}">name : {{row.name}}</a></h2>
        </li>
    {% endfor %}
    </ul>
{% endblock content%}t %}